name: Sync Upstream (musicdl)

on:
  schedule:
    - cron: '0 2 * * *'      # 每天北京时间早上10点
  workflow_dispatch:

permissions:
  contents: write            # ← 关键：增加写入权限

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sync upstream changes
        uses: aormsby/Fork-Sync-With-Upstream-action@v1
        with:
          upstream_repository: CharlesPikachu/musicdl
          upstream_branch: master
          target_branch: master
          github_token: ${{ secrets.GITHUB_TOKEN }}
